### ISSUE TITLE
Radeon rx 570 8gb oc edition hash rate problem

### ISSUE THREAD

**Issue by Saikatsaha1996** [nanopool/phoenix-miner#6]
Hello i am new... Anyone can please help me.. i got very low hash rate how can i slove this..

![IMG_20201203_010716](https://user-images.githubusercontent.com/72664192/100922925-742a4280-3504-11eb-8841-4f6593a9b67e.jpg)

![IMG_20201203_010657](https://user-images.githubusercontent.com/72664192/100922891-683e8080-3504-11eb-809e-e9da695f8b20.jpg)

![IMG_20201203_005004](https://user-images.githubusercontent.com/72664192/100922856-6379cc80-3504-11eb-9b8e-c583f6750eda.jpg)
![IMG_20201203_010416](https://user-images.githubusercontent.com/72664192/100922886-670d5380-3504-11eb-9ee4-d035c3394c34.jpg)

**Comment by JorgeLuisPenaranda** [comment]
Have you modified the BIOS of your video card? That is required

**Comment by Saikatsaha1996** [comment]
> Have you modified the BIOS of your video card? That is required

Thank you for your reply... But now i got 29mh .. 99w , 67C ... Only problem is memory level timing 2 crashed every time... Only stable performance with memory level timing 1 and automatic

**Comment by Saikatsaha1996** [comment]
Thank you so much for your suggestion...
